M48
; DRILL file {KiCad 7.0.10} date Wednesday, November 06, 2024 at 11:23:29 PM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-11-06T23:23:29-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0394
%
G90
G05
T1
X5.6496Y-3.7583
X5.6496Y-3.8583
X6.0433Y-3.7583
X6.0433Y-3.8583
M30
